FROM golang:1.8

RUN mkdir -p /go/src/app && \
    go get -u github.com/kardianos/govendor

ONBUILD ARG PACKAGE=app
ONBUILD WORKDIR /go/src/${PACKAGE}
ONBUILD COPY . /go/src/${PACKAGE}
ONBUILD RUN govendor sync
ONBUILD RUN go install
